using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;

namespace ECommerce.DAL.Models.IdentityModels
{
    public class ApplicationUser : IdentityUser
    {
        //adding required property on the autogenerated user table "AspNetUsers"

        [Required, MaxLength( 50 )]
        public string FirstName { get; set; }

        [Required, MaxLength( 50 )]
        public string LastName { get; set; }
        public Resturant? Restaurant { get; set; }
        public List<Review> Reviews { get; set; }

        public bool AdminCheck { get; set; }
        public List<RefreshToken> RefreshTokens { get; set; }
    }
}
